# Generated by Django 5.0.6 on 2024-05-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_app', '0002_alter_product_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pimage',
            field=models.ImageField(default=0, upload_to='image'),
            preserve_default=False,
        ),
    ]
